# Executable should be a full path
executable=/home/jsingh/nano-dlm/cluster/run.sh

# Logs
LOGS_DIR=/fast/najroldi/logs/plainLM
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

$n_jobs = 1

# Job requirements
request_memory = 128G
request_cpus = 16
request_gpus = 4
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB" || TARGET.CUDADeviceName == "NVIDIA H100 80GB HBM3")

queue $(n_jobs)
